/*
 * This software is distributed under the MIT License
 *
 * Copyright (c) 2008-2020 Alain Becam
 * 
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:

 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
*/

package com.tgb.subgame.unitspc.sensors;

/**
 * A signal is generated by an active sensor and allows other unit to find the position
 * of the sensor.<br>
 * It can also be generated on purpose!
 * @author Alain Becam
 *
 */
public class Signal
{
	public static final int RADAR=0;
	public static final int SONAR=1;
	public static final int LIGHT=2;
	
	public static final int RADAR_NOISE=10;
	public static final int LOUD_NOISE=2;
	public static final int FLASH_LIGHT=2;
	
	int idOwner; // Id of the owner, ie. the Unit owning the signal creator
	
	int type;
	int typeSource;
	
	int propagationSpeed=1000; // Might be used to determine how well we know we origin
	double timeCreation;
	double timeDispertion;
	
	double xOrigin,yOrigin,zOrigin;
	double orientation, angle;
	
	double power; // Power of the signal, used to see at which distance it can be perceived
	
	/**
	 * @return the angle
	 */
	public double getAngle()
	{
		return angle;
	}
	/**
	 * @param angle the angle to set
	 */
	public void setAngle(double angle)
	{
		this.angle = angle;
	}
	/**
	 * @return the orientation
	 */
	public double getOrientation()
	{
		return this.orientation;
	}
	/**
	 * @param orientation the orientation to set
	 */
	public void setOrientation(double orientation)
	{
		this.orientation = orientation;
	}
	/**
	 * @return the propagationSpeed
	 */
	public int getPropagationSpeed()
	{
		return propagationSpeed;
	}
	/**
	 * @param propagationSpeed the propagationSpeed to set
	 */
	public void setPropagationSpeed(int propagationSpeed)
	{
		this.propagationSpeed = propagationSpeed;
	}
	/**
	 * @return the timeCreation
	 */
	public double getTimeCreation()
	{
		return timeCreation;
	}
	/**
	 * @param timeCreation the timeCreation to set
	 */
	public void setTimeCreation(double timeCreation)
	{
		this.timeCreation = timeCreation;
	}
	/**
	 * @return the timeDispertion
	 */
	public double getTimeDispertion()
	{
		return timeDispertion;
	}
	/**
	 * @param timeDispertion the timeDispertion to set
	 */
	public void setTimeDispertion(double timeDispertion)
	{
		this.timeDispertion = timeDispertion;
	}
	/**
	 * @return the type
	 */
	public int getType()
	{
		return type;
	}
	/**
	 * @param type the type to set
	 */
	public void setType(int type)
	{
		this.type = type;
	}
	/**
	 * @return the xOrigin
	 */
	public double getXOrigin()
	{
		return xOrigin;
	}
	/**
	 * @param origin the xOrigin to set
	 */
	public void setXOrigin(double origin)
	{
		xOrigin = origin;
	}
	/**
	 * @return the yOrigin
	 */
	public double getYOrigin()
	{
		return yOrigin;
	}
	/**
	 * @param origin the yOrigin to set
	 */
	public void setYOrigin(double origin)
	{
		yOrigin = origin;
	}
	/**
	 * @return the zOrigin
	 */
	public double getZOrigin()
	{
		return zOrigin;
	}
	/**
	 * @param origin the zOrigin to set
	 */
	public void setZOrigin(double origin)
	{
		zOrigin = origin;
	}
	
	public void setPosOrigin(double x,double y,double z)
	{
		xOrigin = x;
		yOrigin = y;
		zOrigin = z;
	}
	/**
	 * @return the power
	 */
	public double getPower()
	{
		return power;
	}
	/**
	 * @param power the power to set
	 */
	public void setPower(double power)
	{
		this.power = power;
	}
	
	public int getTypeSource() {
		return typeSource;
	}
	
	public void setTypeSource(int typeSource) {
		this.typeSource = typeSource;
	}
	
	public int getIdOwner()
	{
		return idOwner;
	}
	
	public void setIdOwner(int idOwner)
	{
		this.idOwner = idOwner;
	}
}
